import { Injectable } from '@angular/core';
import { Country } from './advertisement/country';
import { State } from './advertisement/state';
import { Currency } from './advertisement/currency';

@Injectable()
export class SelectService {

  getCountries() {
    return [
     new Country(1, 'INDIA' ),
     new Country(2, 'UK' ),
     new Country(3, 'SINGAPORE' ),
     new Country(4, 'HONG KONG' ),
     new Country(5, 'UAE' ),
     new Country(6, 'USA' ),
    ];
  }
  
  getStates() {
   return [
    new State(1, 6, 'Alabama' ),
    new State(2, 6, 'Alaska' ),
    new State(3, 6, 'Arizona ' ),
    new State(4, 6, 'Arkansas' ),
    new State(5, 6, 'California' ),
    new State(6, 6, 'Colorado ' ),
    new State(7, 6, 'Connecticut ' ),
    new State(8, 6, 'Delaware ' ),
    new State(9, 6,'Florida ' ),
    new State(10, 6, 'Georgia' ),
    new State(11, 6, 'Hawaii ' ),
    new State(12, 6, 'Idaho' ),
    new State(13, 6, 'Illinois ' ),
    new State(14, 6, 'Indiana ' ),
    new State(15, 6, 'Iowa ' ),
    new State(16, 6, 'Kansas' ),
    new State(17, 6, 'Kentucky ' ),
    new State(18, 6, 'Louisiana ' ),
    new State(19, 6, 'Maine' ),
    new State(20, 6, 'Maryland ' ),
    new State(21, 6, 'Massachusetts ' ),
    new State(22, 6, 'Michigan ' ),
    new State(23, 6, 'Minnesota ' ),
    new State(24, 6, 'Mississippi ' ),
    new State(25, 6, 'Missouri ' ),
    new State(26, 6, 'Montana' ),
    new State(27, 6, 'Nebraska' ),
    new State(28, 6, 'Nevada ' ),
    new State(29, 6, 'New Hampshire' ),
    new State(30, 6, 'New Jersey ' ),
    new State(31, 6, 'New Mexico' ),
    new State(32, 6, 'New York' ),
    new State(33, 6, 'North Carolina' ),
    new State(34, 6, 'North Dakota' ),
    new State(35, 6, 'Ohio ' ),
    new State(36, 6, 'Oklahoma ' ),
    new State(37, 6, 'Oregon ' ),
    new State(38, 6, 'Pennsylvania ' ),
    new State(39, 6, 'Rhode Island' ),
    new State(40, 6, 'South Carolina' ),
    new State(41, 6, 'South Dakota' ),
    new State(42, 6, 'Tennessee' ),
    new State(43, 6, 'Texas' ),
    new State(44, 6, 'Utah ' ),
    new State(45, 6, 'Vermont ' ),
    new State(46, 6, 'Virginia ' ),
    new State(47, 6, 'Washington ' ),
    new State(48, 6, 'West Virginia' ),
    new State(49, 6, 'Wisconsin ' ),
    new State(50, 6, 'Wyoming ' ),
    new State(51, 1, 'Ahmedabad ' ),
    new State(52, 1, 'Allahabad  ' ),
    new State(53, 1, 'Amaravathi  ' ),
    new State(54, 1, 'Bangalore  ' ),
    new State(55, 1, 'Bhopal  ' ),
    new State(56, 1, 'Bhuvaneshwar  ' ),
    new State(57, 1, 'Chandigarh  ' ),
    new State(58, 1, 'Chennai  ' ),
    new State(59, 1, 'Coimbatore  ' ),
    new State(60, 1, 'Delhi  ' ),
    new State(61, 1, 'Goa  ' ),
    new State(62, 1, 'Hyderabad  ' ),
    new State(63, 1, 'Jaipur  ' ),
    new State(64, 1, 'Kanpur  ' ),
    new State(65, 1, 'Kochi  ' ),
    new State(66, 1, 'Kolkata  ' ),
    new State(67, 1, 'Madurai  ' ),
    new State(68, 1, 'Mangalore  ' ),
    new State(69, 1, 'Mumbai  ' ),
    new State(70, 1, 'Mysore  ' ),
    new State(71, 1, 'Nagpur  ' ),
    new State(72, 1, 'Patna  ' ),
    new State(73, 1, 'Pune  ' ),
    new State(74, 1, 'Pondicherry  ' ),
    new State(75, 1, 'Ranchi  ' ),
    new State(76, 1, 'Trichy  ' ),
    new State(77, 1, 'Trivandrum  ' ),
    new State(78, 1, 'Varanasi  ' ),
    new State(79, 1, 'Vijayawada  ' ),
    new State(80, 1, 'Visakhapattnam ' ),
     new State(81, 5, 'Abu Dhabi' ),
     new State(82, 5, 'Ajman'),
     new State(83, 5, 'Dubai' ),
     new State(84, 5, 'Sharjah' ),
     new State(85, 4, 'Hong Kong' ),
     new State(86, 3, 'Singapore' ),
     new State(87, 2, 'England' ),
     new State(88, 2, 'Scotland' ),
     new State(89, 2, 'Wales' ),
    ];
  }
  getCurrencies()
  {
    return [
      new Currency(1,1, 99,'₹ ','INR ₹120' ,'₹ 2.70', '₹ 18.30' ),
      new Currency(2,2, 9,'£ ' ,'GBD £ 10','£ 1', '-'),
      new Currency(3,3, 19,'$ ', 'SGD $20', '$ 1','-'),
      new Currency(4,4, 99,' $ ','HK $100', '$ 1','-'),
      new Currency(5,5, 49,'AED ', 'AED 50', 'AED 1','-'),
      new Currency(6,6, 19,'$ ','USD $20','$ 1' ,'-'),
     ];
  }

}